# Screen Setup
WIDTH, HEIGHT = 600, 600
FPS = 144

# World Setup
COLS, ROWS = 8, 8
SQ_SIZE_X, SQ_SIZE_Y = WIDTH / COLS, HEIGHT / ROWS
SHOW_GRID = True
GRID_WIDTH = 20 // COLS
RULESET = 'B3/S23'

# Colours
CELL_ALIVE = '#000000'
CELL_DEAD = '#f0f0f0'
GRID_COLOUR = '#aaaaaa'