# Screen Setup
WIDTH, HEIGHT = 600, 600
FPS = 144

# World Setup
zoom = 600 // 10
SCROLL_SPEED = 1
WORLD_X, WORLD_Y = 100, 100
COLS, ROWS = WIDTH // zoom, HEIGHT // zoom
SQ_SIZE_X, SQ_SIZE_Y = WIDTH / COLS, HEIGHT / ROWS
SHOW_GRID = True
GRID_WIDTH = zoom // 20

# Colours
CELL_ALIVE = '#000000'
CELL_DEAD = '#f0f0f0'
GRID_COLOUR = '#aaaaaa'